from typing import Callable, Dict, Any

class Listener:
    def __init__(self) -> None: ...
    def on(self, event: str, cb: Callable[[Dict[str, Any]], None]) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
