[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = ["W391"]

[tool.ruff.lint.per-file-ignores]
"py-raildriver-master/raildriver/__init__.py" = ["F401", "F403"]

[tool.flake8]
max-line-length = 100
extend-ignore = "W391"
