[tool.pytest.ini_options]
addopts = "-q -m real"
markers = [
	"integration: pruebas que requieren datos reales en data/ (se omiten en CI)",
	"real: pruebas que requieren hardware/DLL real (RailDriver)"
]
filterwarnings = [
	"ignore::DeprecationWarning"
]
[tool.ruff]
line-length = 120

[tool.ruff.lint]


[tool.ruff.lint.per-file-ignores]


[tool.flake8]
max-line-length = 120
