[tool.ruff]
line-length = 120

[tool.flake8]
max-line-length = 120
extend-ignore = "E203"

[tool.pytest.ini_options]
addopts = "-q -m real"
markers = [
    "integration: pruebas que requieren datos reales en data/ (se omiten en CI)",
    "real: pruebas que requieren hardware/DLL real (RailDriver)",
]
filterwarnings = [
    "ignore::DeprecationWarning",
]

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120

