from typing import Any, Dict, Iterable, List, Tuple


class RailDriver:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def set_rail_driver_connected(self, v: bool) -> None: ...

    def get_controller_list(self) -> Iterable[Tuple[str, int]]: ...

    def get_current_controller_value(self, idx: int) -> float: ...

    def set_controller_value(self, idx: int, val: float) -> None: ...

    def get_current_coordinates(self) -> List[float]: ...

    def get_current_heading(self) -> float: ...

    def get_current_gradient(self) -> float: ...

    def get_current_fuel_level(self) -> float: ...

    def get_current_is_in_tunnel(self) -> bool: ...

    def get_current_time(self) -> Any: ...


class Listener:
    # minimal attributes used by the code
    special_fields: Dict[str, Any]

    def __init__(self, rd: RailDriver, interval: float = 0.2) -> None: ...

    def subscribe(self, names: Iterable[str]) -> None: ...

    def _main_iteration(self) -> None: ...

    current_data: Dict[str, Any]
