name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Lint & Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      TSC_FAKE_RD: '1'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
        shell: bash

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          if (Test-Path 'requirements-dev.txt') { pip install -r requirements-dev.txt }
          if (Test-Path 'requirements.txt') { pip install -r requirements.txt }
        shell: pwsh

      - name: Lint with ruff (Linux)
        if: runner.os == 'Linux'
        run: |
          python -m ruff check .
        shell: bash

      - name: Lint with ruff (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m ruff check .
        shell: pwsh

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: |
          pytest -q
        shell: bash

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        run: |
          pytest -q
        shell: pwsh

