name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install -r requirements-dev.txt
        shell: pwsh

      - name: Ruff
        run: ruff check .

      - name: Flake8
        run: flake8 .

      - name: Mypy
        run: mypy --ignore-missing-imports .

      - name: Pytest
        run: pytest -q

