name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      - name: Ruff
        run: |
          pip install ruff
          ruff check .
      - name: Flake8
        run: |
          pip install flake8
          flake8 .
      - name: Run tests
        run: |
          pip install pytest
          # Run the full test suite (override pytest.ini addopts to include unmarked tests)
          python -m pytest -q -o addopts=
      - name: Run security scenario tests
        run: |
          pip install pytest
          # Explicitly run safety/scenario tests and fail the job if they break
          python -m pytest -q -o addopts= tests/test_rd_client_ack.py tests/test_rd_client_scenarios.py

  safety-tests:
    name: Safety tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest
      - name: Run safety tests
        id: safety
        continue-on-error: true
        run: |
          python -m pytest -q -m safety || true
      - name: Collect diagnostics on failure
        if: steps.safety.outcome != 'success'
        run: |
          mkdir -p artifacts || true
          cp -v data/control_status.json artifacts/ 2>/dev/null || true
          cp -v data/rd_ack.json artifacts/ 2>/dev/null || true
          cp -v data/rd_send.log artifacts/ 2>/dev/null || true
      - name: Upload artifacts
        if: steps.safety.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: safety-diagnostics
          path: artifacts/
