name: CI - not-real tests

on:
  pull_request:
  push:
    branches:
      - main
      - ci/**

jobs:
  test-not-real:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff==0.12.1

      - name: Run tests (not-real)
        run: |
          ruff check .
          python -m pip install pytest
          python -m pytest -q -m "not real"

      - name: Upload pytest results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-not-real-report
          path: .pytest_cache
